config/routes.rb
Rails.application.routes.draw do
  resources :centro_atencions

  resources :categoria

  resources :productos

  get 'inicio/index'

   root 'inicio#index'

end

app/models/centro_atencion.rb
class CentroAtencion < ActiveRecord::Base
end

app/controllers/centro_atencions_controller.rb
require 'fast_stemmer'
require 'classifier.rb'
class CentroAtencionsController < ApplicationController
  before_action :set_centro_atencion, only: [:show, :edit, :update, :destroy]

  # GET /centro_atencions
  # GET /centro_atencions.json
  def index
    @centro_atencions = CentroAtencion.all
  end

  # GET /centro_atencions/1
  # GET /centro_atencions/1.json
  def show
  end

  # GET /centro_atencions/new
  def new
    @centro_atencion = CentroAtencion.new
  end

  # GET /centro_atencions/1/edit
  def edit
  end

  # POST /centro_atencions
  # POST /centro_atencions.json
  def create
    @centro_atencion = CentroAtencion.new(centro_atencion_params)
    #@hola = 'prueba en donde estoy'
    respond_to do |format|
      if @centro_atencion.save
        format.html { redirect_to @centro_atencion, notice: 'Centro atencion was successfully created.' }
        format.json { render :show, status: :created, location: @centro_atencion }
      else
        format.html { render :new }
        format.json { render json: @centro_atencion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /centro_atencions/1
  # PATCH/PUT /centro_atencions/1.json
  def update
    respond_to do |format|
      if @centro_atencion.update(centro_atencion_params)
        format.html { redirect_to @centro_atencion, notice: 'Centro atencion was successfully updated.' }
        format.json { render :show, status: :ok, location: @centro_atencion }
      else
        format.html { render :edit }
        format.json { render json: @centro_atencion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /centro_atencions/1
  # DELETE /centro_atencions/1.json
  def destroy
    @centro_atencion.destroy
    respond_to do |format|
      format.html { redirect_to centro_atencions_url, notice: 'Centro atencion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_centro_atencion
      @centro_atencion = CentroAtencion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def centro_atencion_params
      params.require(:centro_atencion).permit(:categoria, :servicio)
    end
end

app/helpers/centro_atencions_helper.rb
module CentroAtencionsHelper
end

app/views/centro_atencions/_form.html.erb
<%= form_for(@centro_atencion) do |f| %>
  <% if @centro_atencion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@centro_atencion.errors.count, "error") %> prohibited this centro_atencion from being saved:</h2>

      <ul>
      <% @centro_atencion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="field">

    <%= xxx = text_field :cliente, :nombre %>

    <%= session[:cliente]=params[:cliente]%>
    <%=  params[:clie]=session[:clie] %>

	  <% @b = Classifier::Bayes.new 'soporte', 'reparacion' %>
	  <% @b.train_soporte "para soporte y asistencia" %>
	  <% @b.train_reparacion "reparacion y mantemiento de equipo de computo" %>
	  <%= f.label :servicio %><br>
	  <%= @texto = f.text_field :servicio, :value => "necesito reparar mi equipo de computo" %>
  </div>

  <div class="field">
  	<%= f.label :categoria %><br>
  	<% @u = @b.classify @texto %>
    <%= f.text_field :categoria, :value => @u %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>  
<% end %>

app/views/centro_atencions/edit.html.erb
<h1>Editing centro_atencion</h1>

<%= render 'form' %>

<%= link_to 'Show', @centro_atencion %> |
<%= link_to 'Back', centro_atencions_path %>

app/views/centro_atencions/index.html.erb
<h1>Centro de servicio</h1>

<table>
  <thead>
    <tr>
      <th>Categoria</th>
      <th>Servicio</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @centro_atencions.each do |centro_atencion| %>
      <tr>
        <td><%= centro_atencion.categoria %></td>
        <td><%= centro_atencion.servicio %></td>
        <td><%= link_to 'Ver', centro_atencion %></td>
        <td><%= link_to 'Editar', edit_centro_atencion_path(centro_atencion) %></td>
        <td><%= link_to 'Eliminar', centro_atencion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Servicio', new_centro_atencion_path %>

app/views/centro_atencions/new.html.erb
<h1>Nuevo servicio</h1>

<%= render 'form' %>
<%= link_to 'Back', centro_atencions_path %>

app/views/centro_atencions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Categoria:</strong>
  <%= @centro_atencion.categoria %>
</p>

<p>
  <strong>Servicio:</strong>
  <%= @centro_atencion.servicio %>
</p>

<%= link_to 'Edit', edit_centro_atencion_path(@centro_atencion) %> |
<%= link_to 'Back', centro_atencions_path %>