config/routes.rb
Rails.application.routes.draw do
  resources :centro_atencions

  resources :categoria

  resources :productos

  get 'inicio/index'

   root 'inicio#index'

end

app/controllers/categoria_controller.rb
class CategoriaController < ApplicationController
  before_action :set_categorium, only: [:show, :edit, :update, :destroy]

  # GET /categoria
  # GET /categoria.json
  def index
    @categoria = Categorium.all
  end

  # GET /categoria/1
  # GET /categoria/1.json
  def show
  end

  # GET /categoria/new
  def new
    @categorium = Categorium.new
  end

  # GET /categoria/1/edit
  def edit
  end

  # POST /categoria
  # POST /categoria.json
  def create
    @categorium = Categorium.new(categorium_params)

    respond_to do |format|
      if @categorium.save
        format.html { redirect_to @categorium, notice: 'Categorium was successfully created.' }
        format.json { render :show, status: :created, location: @categorium }
      else
        format.html { render :new }
        format.json { render json: @categorium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categoria/1
  # PATCH/PUT /categoria/1.json
  def update
    respond_to do |format|
      if @categorium.update(categorium_params)
        format.html { redirect_to @categorium, notice: 'Categorium was successfully updated.' }
        format.json { render :show, status: :ok, location: @categorium }
      else
        format.html { render :edit }
        format.json { render json: @categorium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categoria/1
  # DELETE /categoria/1.json
  def destroy
    @categorium.destroy
    respond_to do |format|
      format.html { redirect_to categoria_url, notice: 'Categorium was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_categorium
      @categorium = Categorium.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def categorium_params
      params.require(:categorium).permit(:cate)
    end
end

app/helpers/categoria_helper.rb
module CategoriaHelper
end

app/views/categoria/_form.html.erb
<%= form_for(@categorium) do |f| %>
  <% if @categorium.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@categorium.errors.count, "error") %> prohibited this categorium from being saved:</h2>

      <ul>
      <% @categorium.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cate %><br>
    <%= f.text_field :cate %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categoria/edit.html.erb
<h1>Editing categorium</h1>

<%= render 'form' %>

<%= link_to 'Show', @categorium %> |
<%= link_to 'Back', categoria_path %>

app/views/categoria/index.html.erb
<h1>Listing categoria</h1>

<table>
  <thead>
    <tr>
      <th>Cate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categoria.each do |categorium| %>
      <tr>
        <td><%= categorium.cate %></td>
        <td><%= link_to 'Show', categorium %></td>
        <td><%= link_to 'Edit', edit_categorium_path(categorium) %></td>
        <td><%= link_to 'Destroy', categorium, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Categorium', new_categorium_path %>

app/views/categoria/new.html.erb
<h1>New categorium</h1>

<%= render 'form' %>

<%= link_to 'Back', categoria_path %>

app/views/categoria/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cate:</strong>
  <%= @categorium.cate %>
</p>

<%= link_to 'Edit', edit_categorium_path(@categorium) %> |
<%= link_to 'Back', categoria_path %>