config/routes.rb
Rails.application.routes.draw do
  resources :centro_atencions

  resources :categoria

  resources :productos

  get 'inicio/index'

   root 'inicio#index'

end

app/models/producto.rb
class Producto < ActiveRecord::Base
end

app/controllers/productos_controller.rb
require 'jaccard.rb'
load 'ordenamiento.rb'
class ProductosController < ApplicationController
  before_action :set_producto, only: [:show, :edit, :update, :destroy]

  # GET /productos
  # GET /productos.json
  def index
    @productos = Producto.all
  end

  # GET /productos/1
  # GET /productos/1.json
  def show
    @productos = Producto.all
    @producto = Producto.find(params[:id])
    @ids = []
    @parecidos = []

    @productos.each do |prod|
          @ids.push(prod.id)
          @parecidos.push(Jaccard::coefficient(prod.descripcion.split(" "), @producto.descripcion.split(" ")))
    end

    @ordenInicial = []
    @ordenado = @parecidos.quick_sort
    #@ordenadoParecidos = []
    incremento = 0
    while incremento < @parecidos.length
      @ordenInicial.push( {incremento => @parecidos[incremento]})
      incremento += 1
    end

  end

  # GET /productos/new
  def new
    @producto = Producto.new
  end

  # GET /productos/1/edit
  def edit
  end

  # POST /productos
  # POST /productos.json
  def create
    @producto = Producto.new(producto_params)

    respond_to do |format|
      if @producto.save
        format.html { redirect_to @producto, notice: 'Producto was successfully created.' }
        format.json { render :show, status: :created, location: @producto }
      else
        format.html { render :new }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /productos/1
  # PATCH/PUT /productos/1.json
  def update
    respond_to do |format|
      if @producto.update(producto_params)
        format.html { redirect_to @producto, notice: 'Producto was successfully updated.' }
        format.json { render :show, status: :ok, location: @producto }
      else
        format.html { render :edit }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productos/1
  # DELETE /productos/1.json
  def destroy
    @producto.destroy
    respond_to do |format|
      format.html { redirect_to productos_url, notice: 'Producto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_producto
      @producto = Producto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def producto_params
      params.require(:producto).permit(:productoName, :descripcion)
    end
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/views/productos/_form.html.erb
<%= form_for(@producto) do |f| %>
  <% if @producto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@producto.errors.count, "error") %> prohibited this producto from being saved:</h2>

      <ul>
      <% @producto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :productoName %><br>
    <%= f.text_field :productoName %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br>
    <%= f.text_area :descripcion %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/productos/edit.html.erb
<h1>Editing producto</h1>

<%= render 'form' %>

<%= link_to 'Show', @producto %> |
<%= link_to 'Back', productos_path %>

app/views/productos/index.html.erb
<h1>Productos Parecidos</h1>
<table>
  <thead>
    <tr>
      <th>Producto</th>
      <th>Descripcion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @productos.each do |producto| %>
      <tr>
        <td><%= producto.productoName %></td>
        <td><%= producto.descripcion %></td>
        <td><%= link_to 'Mostrar', producto %></td>
        <td><%= link_to 'Editar', edit_producto_path(producto) %></td>
        <td><%= link_to 'Eliminar', producto, method: :delete, data: { confirm: 'Esta seguro de eliminar?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'Nueo Producto', new_producto_path %>

app/views/productos/new.html.erb
<h1>New producto</h1>

<%= render 'form' %>

<%= link_to 'Back', productos_path %>

app/views/productos/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Productoname:</strong>
  <%= @producto.productoName %>
</p>
<p>
  <strong>Descripcion:</strong>
  <%= @producto.descripcion %>
</p>
<table>
  <thead>
    <tr>
      <th>Parecidos</th>
      <th>Producto</th>
      <th>Descripcion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
  	<% @reve = @productos.length %>
  
	<%contador = 0%>
    <% @productos.each do |producto| %>
      <tr>
      	<%if @ids[contador] == producto.id and contador <= 10%>
				<td><%= @ordenado[@reve] %></td>
		        <td><%= producto.productoName %></td>
		        <td><%= producto.descripcion %></td>
	        <%contador += 1%>
	        <%@reve -= 1%>
	   	<%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Edit', edit_producto_path(@producto) %> |
<%= link_to 'Back', productos_path %>